# Development stage dengan air untuk hot reload
FROM golang:1.25.6-alpine

WORKDIR /app

# Install air, git, dan swag
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

# Copy go mod
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
